name: Code quality

on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Install lib dependencies
        uses: bahmutov/npm-install@v1

      # - name: Test code
      #   run: yarn test --coverage

      - name: Test code
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn jest
          skip-step: install

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v5

      - name: Lint code
        run: yarn lint

      - name: Format code
        run: yarn prettier --check .

      - name: Typecheck code
        run: yarn tsc

      - name: Run performance tests
        run: ./perf-tests.sh

      # - name: Run Danger.js
      #   run: yarn danger ci
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Post performance test results
        uses: mshick/add-pr-comment@v2
        with:
          message-path: '.reassure/output.md'
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
